name = "10xdevs-house-flow"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[[kv_namespaces]]
binding = "SESSION"
id = "175903cc42014f8a9760c1b92f004591"